### ISSUE TITLE
Didn't works on PRUSA i3 MK2

### ISSUE THREAD

**Issue by bionno** [cesarvandevelde/OctoPrint-M73Progress#2]

**Comment by bionno** [comment]
HEllo, i've installed on Octoprint and connected to my printer PRUSA i3 MK2 but the progress did not shown .

Any clue to debug ?

**Comment by cesarvandevelde** [comment]
Try manually entering `M73 P50` into the terminal and see if that updates the progress bar. If not, the issue is with your firmware. I took a quick glance at the Prusa Firmware repository, and I suspect it does not support the M73 command.

**Comment by bionno** [comment]
The problem i think is inside the plugin because  tried another plugin and
that works fine.


Il giorno ven 19 gen 2018 alle ore 08:37 Cesar <notifications@github.com>
ha scritto:

**Comment by cesarvandevelde** [comment]
As far as I'm aware, this is the only plugin that outputs `M73` commands to update the display's progress bar. Other plugins use `M117` (set LCD message) to output a progress message to the display. As noted in the plugin's readme, not all firmwares support the M73 command. If nothing happens when you enter `M73 P50` into the OctoPrint terminal, then that means your firmware does not support the command.

**Comment by bionno** [comment]
Yes , sorry i read this too late, i'm using a plugin that push the M117
command .

Thanks again.
A.


Il giorno ven 19 gen 2018 alle ore 09:59 Cesar <notifications@github.com>
ha scritto:
